# Start with a base image
FROM node:22-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json to install dependencies
COPY package*.json ./

# Install dependencies
RUN npm install
RUN npm install -g nodemon

# Copy the rest of the application code
COPY . .

# Expose a port to access the backend
EXPOSE 4000           

# Start the backend server
CMD ["nodemon", "server.js"]
